# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestJointestmeeting():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_jointestmeeting(self):
    self.driver.get("https://www.webex.com/test-meeting.html")
    self.driver.set_window_size(1440, 797)
    self.driver.find_element(By.ID, "full-name").click()
    self.driver.find_element(By.ID, "full-name").click()
    element = self.driver.find_element(By.ID, "full-name")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "full-name").send_keys("Gerard Kensington")
    self.driver.find_element(By.ID, "email-address").send_keys("gkens@actionchaser.com")
    self.driver.find_element(By.CSS_SELECTOR, ".form_button").click()
    self.driver.find_element(By.ID, "push_download_webapp_buttom_join_link").click()
    self.driver.switch_to.frame(3)
    self.driver.find_element(By.CSS_SELECTOR, ".style-arrow-2f8xt > .style-icon-2HDxh").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".style-arrow-2f8xt > .style-icon-2HDxh")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3)").click()
    self.driver.find_element(By.ID, "interstitial_join_btn").click()
  
